# Generated by Django 4.2.13 on 2024-06-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
    ]
